server:
  port: 9090
spring:
  application:
    name: EUREKA-CLIENT
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  cloud:
loadbalancer:
  retry:
    enabled: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

fegin:
  hystrix:
    enabled: true