@startuml
DefaultMQPushConsumerImpl -> DefaultMQPushConsumerImpl:客户端start启动
DefaultMQPushConsumerImpl -> MQClientInstance:rebalanceImmediately立刻rebalance
MQClientInstance -> MQClientInstance:遍历consumerTable，调用每个group的DefaultMQPushConsumer.RebalanceImpl.dobalance
MQClientInstance -> DefaultMQPushConsumer.RebalanceImpl: 对DefaultMQPushConsumer 下的每个topic进行rebalance
DefaultMQPushConsumer.RebalanceImpl-> DefaultMQPushConsumer.RebalanceImpl:
DefaultMQPushConsumer.RebalanceImpl-> DefaultMQPushConsumer.RebalanceImpl:
DefaultMQPushConsumer.RebalanceImpl-> DefaultMQPushConsumer.RebalanceImpl:
DefaultMQPushConsumer.RebalanceImpl-> DefaultMQPushConsumer.RebalanceImpl:
DefaultMQPushConsumer.RebalanceImpl-> DefaultMQPushConsumer.RebalanceImpl:

@enduml